import type { BackgroundWallpaperConfig } from "@/types/config";

export const backgroundWallpaper: BackgroundWallpaperConfig = {
	mode: "banner",
	switchable: true,
	src: {
		desktop: [
			"/assets/images/wallpapers/bg_1.webp",
			"/assets/images/wallpapers/bg_10.webp",
			"/assets/images/wallpapers/bg_11.webp",
			"/assets/images/wallpapers/bg_12.webp",
			"/assets/images/wallpapers/bg_13.webp",
			"/assets/images/wallpapers/bg_14.webp",
			"/assets/images/wallpapers/bg_15.webp",
			"/assets/images/wallpapers/bg_16.webp",
			"/assets/images/wallpapers/bg_17.webp",
			"/assets/images/wallpapers/bg_18.webp",
			"/assets/images/wallpapers/bg_19.webp",
			"/assets/images/wallpapers/bg_2.webp",
			"/assets/images/wallpapers/bg_20.webp",
			"/assets/images/wallpapers/bg_21.webp",
			"/assets/images/wallpapers/bg_22.webp",
			"/assets/images/wallpapers/bg_23.webp",
			"/assets/images/wallpapers/bg_24.webp",
			"/assets/images/wallpapers/bg_25.webp",
			"/assets/images/wallpapers/bg_26.webp",
			"/assets/images/wallpapers/bg_27.webp",
			"/assets/images/wallpapers/bg_28.webp",
			"/assets/images/wallpapers/bg_29.webp",
			"/assets/images/wallpapers/bg_3.webp",
			"/assets/images/wallpapers/bg_30.webp",
			"/assets/images/wallpapers/bg_31.webp",
			"/assets/images/wallpapers/bg_32.webp",
			"/assets/images/wallpapers/bg_33.webp",
			"/assets/images/wallpapers/bg_34.webp",
			"/assets/images/wallpapers/bg_35.webp",
			"/assets/images/wallpapers/bg_36.webp",
			"/assets/images/wallpapers/bg_37.webp",
			"/assets/images/wallpapers/bg_38.webp",
			"/assets/images/wallpapers/bg_39.webp",
			"/assets/images/wallpapers/bg_4.webp",
			"/assets/images/wallpapers/bg_40.webp",
			"/assets/images/wallpapers/bg_41.webp",
			"/assets/images/wallpapers/bg_42.webp",
			"/assets/images/wallpapers/bg_43.webp",
			"/assets/images/wallpapers/bg_44.webp",
			"/assets/images/wallpapers/bg_45.webp",
			"/assets/images/wallpapers/bg_46.webp",
			"/assets/images/wallpapers/bg_47.webp",
			"/assets/images/wallpapers/bg_48.webp",
			"/assets/images/wallpapers/bg_49.webp",
			"/assets/images/wallpapers/bg_5.webp",
			"/assets/images/wallpapers/bg_50.webp",
			"/assets/images/wallpapers/bg_51.webp",
			"/assets/images/wallpapers/bg_52.webp",
			"/assets/images/wallpapers/bg_6.webp",
			"/assets/images/wallpapers/bg_7.webp",
			"/assets/images/wallpapers/bg_8.webp",
			"/assets/images/wallpapers/bg_9.webp"
		],
		mobile: [
			"/assets/images/wallpapers/bg_1.webp",
			"/assets/images/wallpapers/bg_10.webp",
			"/assets/images/wallpapers/bg_11.webp",
			"/assets/images/wallpapers/bg_12.webp",
			"/assets/images/wallpapers/bg_13.webp",
			"/assets/images/wallpapers/bg_14.webp",
			"/assets/images/wallpapers/bg_15.webp",
			"/assets/images/wallpapers/bg_16.webp",
			"/assets/images/wallpapers/bg_17.webp",
			"/assets/images/wallpapers/bg_18.webp",
			"/assets/images/wallpapers/bg_19.webp",
			"/assets/images/wallpapers/bg_2.webp",
			"/assets/images/wallpapers/bg_20.webp",
			"/assets/images/wallpapers/bg_21.webp",
			"/assets/images/wallpapers/bg_22.webp",
			"/assets/images/wallpapers/bg_23.webp",
			"/assets/images/wallpapers/bg_24.webp",
			"/assets/images/wallpapers/bg_25.webp",
			"/assets/images/wallpapers/bg_26.webp",
			"/assets/images/wallpapers/bg_27.webp",
			"/assets/images/wallpapers/bg_28.webp",
			"/assets/images/wallpapers/bg_29.webp",
			"/assets/images/wallpapers/bg_3.webp",
			"/assets/images/wallpapers/bg_30.webp",
			"/assets/images/wallpapers/bg_31.webp",
			"/assets/images/wallpapers/bg_32.webp",
			"/assets/images/wallpapers/bg_33.webp",
			"/assets/images/wallpapers/bg_34.webp",
			"/assets/images/wallpapers/bg_35.webp",
			"/assets/images/wallpapers/bg_36.webp",
			"/assets/images/wallpapers/bg_37.webp",
			"/assets/images/wallpapers/bg_38.webp",
			"/assets/images/wallpapers/bg_39.webp",
			"/assets/images/wallpapers/bg_4.webp",
			"/assets/images/wallpapers/bg_40.webp",
			"/assets/images/wallpapers/bg_41.webp",
			"/assets/images/wallpapers/bg_42.webp",
			"/assets/images/wallpapers/bg_43.webp",
			"/assets/images/wallpapers/bg_44.webp",
			"/assets/images/wallpapers/bg_45.webp",
			"/assets/images/wallpapers/bg_46.webp",
			"/assets/images/wallpapers/bg_47.webp",
			"/assets/images/wallpapers/bg_48.webp",
			"/assets/images/wallpapers/bg_49.webp",
			"/assets/images/wallpapers/bg_5.webp",
			"/assets/images/wallpapers/bg_50.webp",
			"/assets/images/wallpapers/bg_51.webp",
			"/assets/images/wallpapers/bg_52.webp",
			"/assets/images/wallpapers/bg_6.webp",
			"/assets/images/wallpapers/bg_7.webp",
			"/assets/images/wallpapers/bg_8.webp",
			"/assets/images/wallpapers/bg_9.webp"
		]
	},
	banner: {
		position: "center",
		homeText: {
			enable: true,
			switchable: true,
			title: "Lovely Xiyue!",
			titleSize: "3.8rem",
			subtitle: [
				"欢迎来到汐月的专属领域 ~",
				"在草莓流心的甜味里，寻找生活的真谛",
				"薰衣草茶的温热，是最安静的陪伴",
				"比起繁杂的代码，我更在乎当下的风景",
				"不准盯着我看太久哦，真是的",
				"在这个光影的缝隙里，私藏属于我们的温柔"
			],
			subtitleSize: "1.5rem",
			typewriter: {
				enable: true,
				speed: 100,
				deleteSpeed: 50,
				pauseTime: 2000,
			},
		},
		credit: {
			enable: { desktop: true, mobile: true },
			text: { desktop: "Xiyue Wallpapers", mobile: "Xiyue Wallpapers" },
			url: { desktop: "", mobile: "" }
		},
		navbar: {
			transparentMode: "semifull",
			enableBlur: true,
			blur: 3,
		},
		waves: {
			enable: { desktop: true, mobile: true },
			switchable: true,
		},
	},
	overlay: {
		zIndex: -1,
		opacity: 0.8,
		blur: 1,
	},
};
